# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: undertow.js CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-test-matrix:
    name: ${{ matrix.jdk-distribution }}-${{ matrix.jdk-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk-distribution: [temurin]
        jdk-version: [8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk-distribution }} ${{ matrix.jdk-version }}
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.jdk-distribution }}
        java-version: ${{ matrix.jdk-version }}
    - name: Run Tests
      run: mvn -ntp -U -B -fae clean install
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-${{ matrix.jdk-distribution }}-${{ matrix.jdk-version }}-${{ matrix.os }}
        path: '**/surefire-reports/*.txt'
